server:
  host: 0.0.0.0
  port: 8000

pipeline_config_dir: ./pipelines

database:
  url: sqlite+aiosqlite:///./runs.db

executors:
  openclaw:
    base_url: http://localhost:18789
    hooks_token: ${OPENCLAW_HOOKS_TOKEN}

notifications:
  telegram:
    bot_token: 8637524420:AAHk9AkRxHEYSWdzIpTTiEGteUYRvtjn680
    chat_id: 8696664118

logging:
  level: INFO
