"""baseline

Full current schema (every table, column, and index a fully-up-to-date
pre-Alembic deployment already has) — see SPEC-alembic-migrations.md §2.
Existing databases never run this revision's DDL directly: database.py's
adoption logic stamps them at this revision after bringing them to this exact
shape via the legacy shim. Only a brand-new, empty database actually runs it.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-06 17:14:27.611457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_version_snapshots',
    sa.Column('agent_version', sa.String(), nullable=False),
    sa.Column('agent', sa.String(), nullable=False),
    sa.Column('soul_md', sa.Text(), nullable=True),
    sa.Column('agent_yaml', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('agent_version')
    )
    op.create_index(op.f('ix_agent_version_snapshots_agent'), 'agent_version_snapshots', ['agent'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pipeline_name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('normalised_context', sa.Text(), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('parent_run_id', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_fingerprint'), 'pipeline_runs', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_parent_run_id'), 'pipeline_runs', ['parent_run_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_stage'), 'pipeline_runs', ['stage'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_team'), 'pipeline_runs', ['team'], unique=False)
    # Not declared on the model — closes the dedup TOCTOU race (README §3a) at
    # the DB layer. NULLs are never equal in a unique index, so fingerprint=None
    # rows (sub-pipelines, dedup opt-outs) are unaffected. Both dialect kwargs
    # are needed: postgresql_where alone is silently ignored on SQLite.
    op.create_index(
        'ix_pipeline_runs_running_fingerprint', 'pipeline_runs',
        ['pipeline_name', 'fingerprint'], unique=True,
        postgresql_where=sa.text("status = 'running'"),
        sqlite_where=sa.text("status = 'running'"),
    )
    op.create_table('run_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('pipeline_name', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_feedback_pipeline_name'), 'run_feedback', ['pipeline_name'], unique=False)
    op.create_index(op.f('ix_run_feedback_run_id'), 'run_feedback', ['run_id'], unique=True)
    op.create_table('step_prompt_versions',
    sa.Column('prompt_hash', sa.String(), nullable=False),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('prompt_hash')
    )
    op.create_index(op.f('ix_step_prompt_versions_step_name'), 'step_prompt_versions', ['step_name'], unique=False)
    op.create_table('pipeline_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('executor', sa.String(), nullable=False),
    sa.Column('agent', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('prompt_hash', sa.String(), nullable=True),
    sa.Column('agent_version', sa.String(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('parsed_output', sa.Text(), nullable=True),
    sa.Column('verifier_output', sa.Text(), nullable=True),
    sa.Column('verifier_mode', sa.String(), nullable=True),
    sa.Column('verifier_agent', sa.String(), nullable=True),
    sa.Column('verifier_model', sa.String(), nullable=True),
    sa.Column('verifier_provider', sa.String(), nullable=True),
    sa.Column('verifier_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('primary_confidence', sa.Float(), nullable=True),
    sa.Column('verifier_confidence', sa.Float(), nullable=True),
    sa.Column('effective_confidence', sa.Float(), nullable=True),
    sa.Column('grounding_score', sa.Float(), nullable=True),
    sa.Column('trust_report', sa.Text(), nullable=True),
    sa.Column('deterministic_passed', sa.Boolean(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('artifacts', sa.Text(), nullable=True),
    sa.Column('agent_trace', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('verifier_input_tokens', sa.Integer(), nullable=True),
    sa.Column('verifier_output_tokens', sa.Integer(), nullable=True),
    sa.Column('grounding_model', sa.String(), nullable=True),
    sa.Column('grounding_provider', sa.String(), nullable=True),
    sa.Column('grounding_input_tokens', sa.Integer(), nullable=True),
    sa.Column('grounding_output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_steps_agent_version'), 'pipeline_steps', ['agent_version'], unique=False)
    op.create_index(op.f('ix_pipeline_steps_prompt_hash'), 'pipeline_steps', ['prompt_hash'], unique=False)
    op.create_table('step_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('step_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('pipeline_name', sa.String(), nullable=False),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['pipeline_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_feedback_pipeline_name'), 'step_feedback', ['pipeline_name'], unique=False)
    op.create_index(op.f('ix_step_feedback_run_id'), 'step_feedback', ['run_id'], unique=False)
    op.create_index(op.f('ix_step_feedback_step_id'), 'step_feedback', ['step_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_step_feedback_step_id'), table_name='step_feedback')
    op.drop_index(op.f('ix_step_feedback_run_id'), table_name='step_feedback')
    op.drop_index(op.f('ix_step_feedback_pipeline_name'), table_name='step_feedback')
    op.drop_table('step_feedback')
    op.drop_index(op.f('ix_pipeline_steps_prompt_hash'), table_name='pipeline_steps')
    op.drop_index(op.f('ix_pipeline_steps_agent_version'), table_name='pipeline_steps')
    op.drop_table('pipeline_steps')
    op.drop_index(op.f('ix_step_prompt_versions_step_name'), table_name='step_prompt_versions')
    op.drop_table('step_prompt_versions')
    op.drop_index(op.f('ix_run_feedback_run_id'), table_name='run_feedback')
    op.drop_index(op.f('ix_run_feedback_pipeline_name'), table_name='run_feedback')
    op.drop_table('run_feedback')
    op.drop_index(op.f('ix_pipeline_runs_team'), table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_running_fingerprint', table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_stage'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_parent_run_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_fingerprint'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_agent_version_snapshots_agent'), table_name='agent_version_snapshots')
    op.drop_table('agent_version_snapshots')
    # ### end Alembic commands ###
